# Data Analyzing

Load and inspect the processed datasets. (from raw+processed output. (they are supposed to be in the "/" folder of the project))

In [ ]:
import pandas as pd

pd.options.display.float_format = '{:.2f}'.format

burnout = pd.read_csv('burnout_processed.csv')
health  = pd.read_csv('health_processed.csv', parse_dates=['date'])

print('Burnout:', burnout.shape)
print('Health: ', health.shape)

Burnout: (1000000, 22)
Health:  (577, 10)

## Burnout Dataset – Basic Info

This gives the columns and the dataset size which is 1 million.

In [7]:
burnout.info()
print('\nMissing values:')
print(burnout.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 22 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   age                   1000000 non-null  int64
 1   gender                1000000 non-null  str
 2   academic_year         1000000 non-null  int64
 3   study_hours_per_day   1000000 non-null  float64
 4   exam_pressure         1000000 non-null  float64
 5   academic_performance  1000000 non-null  float64
 6   stress_level          1000000 non-null  float64
 7   anxiety_score         1000000 non-null  float64
 8   depression_score      1000000 non-null  float64
 9   sleep_hours           1000000 non-null  float64
 10  physical_activity     1000000 non-null  float64
 11  social_support        1000000 non-null  float64
 12  screen_time           1000000 non-null  float64
 13  internet_usage        1000000 non-null  float64
 14  financial_stress      1000000 non-null  float64
 15  family_expectation    1000000 non-null  float64
 16  burnout_score         1000000 non-null  float64
 17  mental_health_index   1000000 non-null  float64
 18  risk_level            1000000 non-null  str
 19  dropout_risk          1000000 non-null  float64
 20  risk_level_encoded    1000000 non-null  int64
 21  gender_encoded        1000000 non-null  int64
dtypes: float64(16), int64(4), str(2)
memory usage: 167.8 MB

Missing values:
age                     0
gender                  0
academic_year           0
study_hours_per_day     0
exam_pressure           0
academic_performance    0
stress_level            0
anxiety_score           0
depression_score        0
sleep_hours             0
physical_activity       0
social_support          0
screen_time             0
internet_usage          0
financial_stress        0
family_expectation      0
burnout_score           0
mental_health_index     0
risk_level              0
dropout_risk            0
risk_level_encoded      0
gender_encoded          0
dtype: int64

In [8]:
# This gives a peek into the burnout dataset.
burnout.describe()

,age,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,dropout_risk,risk_level_encoded,gender_encoded
count,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00,1000000.00
mean,23.00,2.50,5.00,6.00,71.00,4.25,2.99,1.27,6.50,3.01,5.00,5.02,5.04,5.00,5.98,1.78,7.02,1.32,0.25,0.56
std,3.74,1.12,1.99,1.55,5.66,1.68,1.51,1.22,1.47,1.46,1.98,1.96,2.16,1.98,1.96,1.66,1.31,1.34,0.47,0.57
min,17.00,1.00,0.00,1.00,42.37,0.00,0.00,0.00,3.00,0.00,0.00,1.00,1.00,0.00,0.00,0.00,1.31,0.00,0.00,0.00
25%,20.00,2.00,3.65,4.94,67.18,3.10,1.92,0.01,5.49,1.99,3.65,3.65,3.49,3.66,4.65,0.12,6.14,0.00,0.00,0.00
50%,23.00,3.00,5.00,6.00,71.00,4.24,2.97,1.05,6.50,3.00,5.00,5.00,5.00,5.00,6.00,1.50,7.07,1.01,0.00,1.00
75%,26.00,4.00,6.35,7.05,74.82,5.39,4.01,2.09,7.51,4.01,6.35,6.35,6.51,6.35,7.35,2.89,7.96,2.17,0.00,1.00
max,29.00,4.00,14.00,10.00,97.25,10.00,10.00,8.53,10.00,7.00,10.00,12.00,14.00,10.00,10.00,10.00,10.00,9.33,2.00,2.00

## Apple Health – Basic Info

This gives the columns and the dataset of my apple_health_daily data.

In [9]:
health.info()
print('\nMissing values:')
print(health.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          577 non-null    datetime64[us]
 1   daily_steps                   577 non-null    float64
 2   avg_heart_rate                7 non-null      float64
 3   resting_heart_rate            2 non-null      float64
 4   hrv                           4 non-null      float64
 5   active_calories               577 non-null    float64
 6   exercise_minutes              577 non-null    float64
 7   distance_km                   577 non-null    float64
 8   is_exam_period                577 non-null    int64
 9   physical_activity_normalized  577 non-null    float64
dtypes: datetime64[us](1), float64(8), int64(1)
memory usage: 45.2 KB

Missing values:
date                              0
daily_steps                       0
avg_heart_rate                  570
resting_heart_rate              575
hrv                             573
active_calories                   0
exercise_minutes                  0
distance_km                       0
is_exam_period                    0
physical_activity_normalized      0
dtype: int64

In [10]:
# This gives a peek into the apple health dataset.
health.describe()

,date,daily_steps,avg_heart_rate,resting_heart_rate,hrv,active_calories,exercise_minutes,distance_km,is_exam_period,physical_activity_normalized
count,577,577.00,7.00,2.00,4.00,577.00,577.00,577.00,577.00,577.00
mean,2025-06-16 00:00:00,10379.62,129.04,88.50,31.96,9.06,0.76,7.54,0.25,4.03
min,2024-09-01 00:00:00,539.00,94.59,74.00,19.88,0.00,0.00,0.38,0.00,0.21
25%,2025-01-23 00:00:00,7245.00,125.74,81.25,21.96,0.00,0.00,5.16,0.00,2.87
50%,2025-06-16 00:00:00,10205.00,132.04,88.50,32.27,0.00,0.00,7.27,0.00,4.04
75%,2025-11-07 00:00:00,13005.00,139.84,95.75,42.27,0.00,0.00,9.47,1.00,5.15
max,2026-03-31 00:00:00,30904.00,145.51,103.00,43.40,1000.93,97.00,26.25,1.00,7.00
std,NaN,4531.46,17.06,20.51,12.41,80.20,7.61,3.48,0.43,1.58